name: clima_v2
description: A new Flutter project.

environment:
  sdk: '>=2.18.1 <3.0.0'
dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.1.0
  geolocator: ^9.0.2
  get: ^4.6.5
  http: ^0.13.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - images/
